/*
* This file was generated by the Gradle 'init' task.
*/
@file:Suppress("SpellCheckingInspection")

import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

plugins {
    java
    `maven-publish`
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("xyz.jpenilla.run-paper") version "1.0.6"
}

repositories {
    // Required for IntellIJ
    mavenLocal() {
        content {
            includeGroup("org.bukkit")
        }
    }

    maven(url = uri("https://papermc.io/repo/repository/maven-public/"))

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public")
    }

    maven {
        url = uri("https://repo.extendedclip.com/content/repositories/placeholderapi/")
        content {
            includeGroup("me.clip")
        }
    }

    mavenCentral()
}

dependencies {
    implementation("org.json", "json", "20190722")
    implementation("org.bstats", "bstats-bukkit", "2.2.1")
    implementation("com.github.stefvanschie.inventoryframework", "IF", "0.10.3")
    implementation("io.papermc", "paperlib", "1.0.7")
    compileOnly("com.github.MilkBowl", "VaultAPI", "1.7")
    compileOnly("me.clip", "placeholderapi", "2.10.8")
    compileOnly("org.jetbrains", "annotations", "22.0.0")
    compileOnly("dev.folia", "folia-api", "1.19.4-R0.1-SNAPSHOT")
}

// Set the default value to the current time as an ISO-8601 string
var time = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME).replace(":", ".")
var buildNumber: String = System.getenv().getOrDefault("BUILD_NUMBER", time)

group = "pw.chew.transmuteit"
version = "0.5.0-b${buildNumber}"
description = "TransmuteIt"

java {
    withSourcesJar()
    withJavadocJar()
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.shadowJar {
    relocate("com.github.stefvanschie.inventoryframework", "pw.chew.transmuteit.inventoryframework")
    relocate("org.bstats", "pw.chew.transmuteit.bstats")
    relocate("io.papermc.lib", "pw.chew.transmuteit.paperlib")
    minimize()
    archiveAppendix.set("")
    archiveClassifier.set("")
}

tasks.runServer {
    minecraftVersion("1.18.1")
}
