name: TransmuteIt
main: pw.chew.transmuteit.TransmuteIt
version: 0.5.0-b${build}
api-version: "1.15"
description: It's just ProjectE Transmutation for Spigot
author: Chewsterchew
folia-supported: true
website: https://github.com/ChewMC/TransmuteIt
softdepend: [Vault, PlaceholderAPI]
commands:
  transmute:
    description: The main command for the plugin.
    aliases:
      - 'tm'
    usage: "Usage: /transmute"
    permission: transmute.main
    permission-message: The admins have revoked your ability to run this command!
  setEMC:
    description: Set the EMC value of the held item.
    usage: "Usage: /setEMC <amount>"
    permission: transmute.admin.setemc
    permission-message: The admins have revoked your ability to run this command!
  getEMC:
    description: Get the EMC value of the held item.
    usage: "Usage: /getEMC"
    permission: transmute.command.getemc
    permission-message: The admins have revoked your ability to run this command!
  emc:
    description: Get your EMC value.
    usage: "Usage: /emc"
    permission: transmute.player.emc
    permission-message: The admins have revoked your ability to run this command!
  discoveries:
    description: Get your discoveries.
    usage: "Usage: /discoveries"
    permission: transmute.player.discoveries
    permission-message: The admins have revoked your ability to run this command!

permissions:
  transmute.player:
    default: true
    children:
      transmute.main: true
      transmute.gui: true
      transmute.command.getemc: true
      transmute.command.getemc.any: true
      transmute.player.emc: true
      transmute.player.discoveries: true
      transmute.command.take: true
      transmute.command.get: true
      transmute.command.analyze: true
      transmute.command.learn: true
      transmute.command.version: true
  transmute.*:
    default: op
    children:
      transmute.admin.setemc: true
      transmute.player: true
      transmute.player.emc.others: true
      transmute.player.discoveries.other: true
      transmute.admin.notices: true
