name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2.3.5
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          cache: 'gradle'
          distribution: 'temurin'
      - name: Build
        run: |
          ./gradlew build --stacktrace
